### ISSUE TITLE
not compatible with client side version of superagent

### ISSUE THREAD

**Issue by xrado** [jpodwys/superagent-cache#17]
The problem is in keygen which is using req.qs for key generation, while client side superagent do not have this property, it holds query params in req._query. Here is mine quick dirty fix https://github.com/xrado/superagent-cache/commit/c716592ad7c8a9db62a174a9bb1b165e0effc111

What are your thoughts?

**Comment by jpodwys** [comment]
This is a good note, thanks! The issue with your code is that, while it fixes the client version, it breaks the node version. I wonder why they named the node and client property sets differently. I'll look into fixing it.

**Comment by jpodwys** [comment]
@xrado I've pushed some updates fixes to the [client-fixes branch](https://github.com/jpodwys/superagent-cache/tree/client-fixes). Please check it out and let me know if it fixes the issues you're seeing. Thanks!

**Comment by jpodwys** [comment]
@xrado Just want to make sure this didn't get lost over the weekend.

**Comment by xrado** [comment]
@jpodwys it wont. I'm just quite busy this days. Btw I've just quickly test your fix branch on a project I'm working on and request didn't get cached anymore. I didn't find out why, so I didn't reply to you jet. Give me a few days.

**Comment by jpodwys** [comment]
Ok thanks for the update!

**Comment by xrado** [comment]
_this.abort() is throwing error in mine client side code
```Cannot read property 'abort' of undefined
    at Request.abort```
preventing getting data from cache

**Comment by jpodwys** [comment]
Is the project you're working on in a public repo? If so, I could pull it down and take a close look at what's going on.

**Comment by xrado** [comment]
No before that I used my fork which is a few commits behind. Repo is company's private. I'll try to put together a small reproducible example.

**Comment by xrado** [comment]
here https://github.com/xrado/superagent-cache-test, I made a small reproducible example. If I replace superagent-cache with my fork, it work just fine, requests get cached

**Comment by jpodwys** [comment]
Thank you! The issue was introduced in `1.0.6`. As you've said, it is indeed the `_this.abort();` call that's causing the issue. After extensive testing, it appears it's no longer needed. I've messaged the person that submitted the PR that added the abort call to make sure it can be removed without causing him problems.

**Comment by jpodwys** [comment]
I'm planning to make a new release on Monday (21 Dec) that fixes the two bugs we've discussed here:

* remove `_this.abort();`
* fix `keygen()` to work with both node and the client

I've tested your superagent-cache-test repo against my latest changes in my client-fixes branch. My results suggest that the changes fix both of the bugs above. Can you please confirm that it fixes the `keygen()` issue you were experiencing with query params?

**Comment by xrado** [comment]
Nice work! yes, everything work as expected, storage option will come handy. That's it, I don't have anything to add. Looking forward for new release.

**Comment by jpodwys** [comment]
Just published `1.3.0`. Please go ahead and close this when you're satisfied with the release. Thank you again for all your help.

**Comment by xrado** [comment]
awesome, I've just updated to 1.3.0 and everything works great. Thanks!
