### ISSUE TITLE
No LICENSE file?

### ISSUE THREAD

**Issue by mvandiest** [jpodwys/superagent-cache#19]
Would love to use the lib. Can you add a license? I would ask the same question of all the cache modules too... Would you prefer separate issues in those repos, or just this one?

Thanks!

**Comment by jpodwys** [comment]
Thanks for the note. I had listed MIT in the package.json of all my repos, but I've now added the actual file to most of my repos including the ones you mentioned.

**Comment by mvandiest** [comment]
Sorry, I didn't peek in the package.json file. Just looked for the LICENSE in root or README...

A release would be nice, but I'm fine with it in the repos for the time being. Thanks for the super-fast response!

**Comment by jpodwys** [comment]
OK all superagent-cache and cache module repos have been published.

**Comment by mvandiest** [comment]
Thanks!
