### ISSUE TITLE
Issue with redirects

### ISSUE THREAD

**Issue by ariutta** [jpodwys/superagent-cache#26]
Hello,

[My library](https://github.com/ariutta/jsonld-rx) needs to use to `res.redirects`. The test suite I need to pass works when I just use `superagent`, but the tests that involve redirects fail when I enable `superagent-cache`.

Here is an example of a failing test from the test suite:  [Loading a document with a redirect should use the redirected URL as document base](https://github.com/json-ld/json-ld.org/blob/b2c57989c1d72faf5d6fe788c0523120d8098136/test-suite/tests/remote-doc-manifest.jsonld#L47).

[This issue](https://github.com/ariutta/jsonld-rx/issues/1) further describes the problem and references my code for enabling `superagent-cache`.

Any tips on getting started with a refactor to handle redirects?

Thanks!

**Comment by jpodwys** [comment]
Thanks for the details! I'll spend some time looking at this tomorrow and I'll hopefully have some info for you by the end of tomorrow or the next day.

**Comment by jpodwys** [comment]
I've added a new branch called `redirects` in which I've added a single unit test that tries a redirect. The test seems to confirm that `superagent-cache` does follow redirects and correctly uses the initial request's key to cache the final request's response. Of course, peer review is always good so please have a look at the new code to see if I've done something wrong or if it can help you.

You can [see the change here](https://github.com/jpodwys/superagent-cache/compare/redirects?expand=1#diff-77db61e6296caa765e08b4db2bab2b0dR117).

**Comment by ariutta** [comment]
Thanks for looking into it. I'll try to get you a relevant test this coming Monday.

**Comment by ariutta** [comment]
I made a pull request with tests for this case: https://github.com/jpodwys/superagent-cache/pull/27

Feel free to refactor the tests, because they are really slow. They should at least be a good start for demonstrating the issue.

You can also view a simplified demo version here that passes for plain `superagent` but fails for `superagent-cache`: https://gist.github.com/ariutta/972aba5adfb4063d1876

Thanks!

**Comment by jpodwys** [comment]
This is great thank you for your help! I may not be able to look at this for a couple of days but I'll get to as soon as I can.

**Comment by jpodwys** [comment]
I apologize that I still haven't gotten to this. I've been quite busy, but I will work on it no later than Tuesday.

**Comment by ariutta** [comment]
No worries -- thanks for the update!

**Comment by jpodwys** [comment]
Thank you for the PR--it demonstrated that superagent-cache returns an empty array for `res.redirects` even when redirects have occurred. (Although it does cache the correct data at the correct address.)

I've pushed a new commit to the `redirects` branch which, I believe, fixes the issue. Please check it out and let me know how it works for you.

The problem was that, since I'm aliasing superagent's `.end()` call and replacing it with my own, when a redirect occurs, superagent-cache forwards the redirect to my `.end()` function which did not have redirect aggregation setup.

Thanks again for the help and great catch!

**Comment by ariutta** [comment]
Thanks for making this update -- it fully solves the issue!

Just a small note: the tests I added (like [this one](https://github.com/jpodwys/superagent-cache/blob/redirects/test/server/caching.js#L216)) are probably too slow to be ideal for unit tests. Maybe your mock server could replicate the redirects?

**Comment by jpodwys** [comment]
Agreed, just wanted to leave what you added intact until you passed off on it. Glad it worked for you!

I've published this to npm in `1.3.4` and gave you a thanks in the [release notes](https://github.com/jpodwys/superagent-cache/releases/tag/1.3.4).

Please close this issue when you're satisfied with the npm release. Nice working with you!

**Comment by ariutta** [comment]
Nice working with you too!
