### ISSUE TITLE
Prepopulate cache without executing query

### ISSUE THREAD

**Issue by jpodwys** [jpodwys/superagent-cache#39]
Sometimes all I want to do is populate a value I already have into the cache at the address superagent-cache would have set it. I can currently do this as follows:

```javascript
superagent
  .get('url')
  .doQuery(false)
  .end(function (err, response, key){
    superagent.cache.set(key, someValue);
  }
);
```

However, it would be nice to have a simpler solution.

**Comment by marybeshaw** [comment]
Could you add a function to get a key for a potential superagent call?  I know you generate a key string using a bunch of data about the superagent call itself... so maybe it's an oversimplification.

`
superagent.cache.set(superagent.getKey('url'), someValue);
`

**Comment by jpodwys** [comment]
I'd might end up providing a .getKey function in place of .end. But that would really only prevent the .doQuery call in the example above as well as providing synchronous execution. If I followed your code snippet, which doesn't seem too difficult, it could require users to manually reformat their data in the event they have headers and params whereas that's already built into query generation. There just may not be a better way to do it than the demo in the issue especially if they want to use .pruneParams and such. 

I think I may just close this. Thanks for your input on this issue and the other one someone submitted this morning.
