### ISSUE TITLE
superagent as peer dependency

### ISSUE THREAD

**Issue by deyhle** [jpodwys/superagent-cache#4]
Wouldn't it be better to have superagent as peer dependency? This way we are free to use the latest superagent version without waiting for an superagent-cache update.

**Comment by jpodwys** [comment]
You can already use whatever version of superagent you want by passing your pre-required superagent variable into superagent-cache's constructor as the first argument as follows:

```javascript
var superagent = require('superagent');
require('superagent-cache')(superagent);
```

When used this way, superagent-cache will simply patch the superagent variable you pass to it.

See the [Various ways of requiring superagent-cache](https://github.com/jpodwys/superagent-cache#various-ways-of-requiring-superagent-cache) section from the documentation for more usage examples.

The version of superagent included in superagent-cache's package.json is simply there for convenience and as a version of superagent that users can be confident works well with superagent-cache.

**Comment by jpodwys** [comment]
Does this resolve your concern?

**Comment by deyhle** [comment]
Yes it does, thank you. Should have fully read the documentation :)

**Comment by jpodwys** [comment]
Great. Glad it's working for you!
