### ISSUE TITLE
Patch a copy of superagent.

### ISSUE THREAD

**Issue by vijayst** [jpodwys/superagent-cache#47]
I want to patch a copy of superagent and not the superagent itself. What I want is this.

Initially, I patch superagent with superagent-cache.

```
import superagent from "superagent"
import superagentCache from "superagent-cache"

superagentCache(superagent);
```

This will patch all other imports of superagent.
`import superagent from "superagent";`

I want to patch a copy of superagent and not the original superagent itself. Is that possible?

**Comment by jpodwys** [comment]
I haven't considered this. May I ask when this would be useful?

**Comment by vijayst** [comment]
mobx-model / API wraps around superagent. I am trying to get superagent-cache to work with mobx-model. The related issue in mobx-model is https://github.com/wearevolt/mobx-model/issues/19

**Comment by jpodwys** [comment]
I looked at the mobx-model package.json, and [it uses superagent `^2.1.0`](https://github.com/wearevolt/mobx-model/blob/master/package.json#L39). I've only been able to ensure that superagent-cache is compatible with superagent `1.x`. I made sure to mention that in [superagent's docs](https://github.com/visionmedia/superagent#plugins), but I should add it to my own docs in a more visible location.

However, I don't see anything in particular in mobx-model's superagent usage that would necessarily conflict with passing in your own superagent-cache, but you would almost certainly need to patch a `1.x` instance to make it work. Or, just don't pass an instance in and allow superagent-cache to create and return one for you.

```javascript
var superagent = require('superagent-cache')();

// Now pass superagent into mobx-model
```

Additionally, I noticed that you need to apply some config to every query. In particular, you named the `forceUpdate` feature. You can do this by passing the `defaults` object as the third param as follows:

```javascript
var superagent = require('superagent-cache')(null, null, {forceUpdate: true});
```

**Comment by vijayst** [comment]
I tried this, but does not seem to work. I used Charles proxy to verify that cache is being used. It could be possible that mobx-model / API does not recognize the option. Let me check that.
```
var superagent = require('superagent-cache')(null, null, {forceUpdate: true});
```

**Comment by jpodwys** [comment]
It's also possible that one of the calls to superagent that mobx-model is using is only available in superagent `2.x`.

If you're able to be more specific about what exactly is not working, I may be able to help more. Otherwise I don't know what the issue is.

**Comment by vijayst** [comment]
I did patch initially with superagent-cache. The superagent is patched. If I use superagent after the patch, it is always patched. I am not able re-patch superagent with the force update flag. Maybe, it does not make sense either. I wish superagent-cache returns patches a copy of superagent and not patch the actual superagent. Maybe, I can do it by cloning superagent and sending the clone to superagent-cache to be patched?

**Comment by jpodwys** [comment]
This isn't an issue of superagent patching a copy. It's an issue of you wanting two copies of a singleton. 

If you're using NPM 2.x, there is a possible way you can have two instances of a singleton. If your package.json requires a different version of superagent than mobx-model does, then you should be able to require your copy and it be independent from the one required by mobx-model. 

I've done this sort of thing once before. I don't recommend this approach, but it might get you what you want.

**Comment by vijayst** [comment]
Thanks @jpodwys. Totally appreciate your help. I will use the mobx-model superagent for the non-cached version and supply the superagent-cache in all get requests (except the refresh). Thanks for your time.

**Comment by jpodwys** [comment]
No problem! As a note, AI believe this easiest way to do this is to just allow mobx-model and superagent-cache to include their own versions of superagent meaning that you don't pass a superagent instance into either of them. superagent-cache relies on a different version internally than mobx-model so it could just work like that.

**Comment by vijayst** [comment]
We have written some framework code written on top of mobx-model / API. All our API actions should happen through that.  If I use superagent-cache and mobx-model / API separately, I will be duplicating the framework code.

**Comment by jpodwys** [comment]
I can only help you if I know what's broken.

Although a quick look at mobx-model's usage of superagent `2.x` in [`src/api.js`](https://github.com/wearevolt/mobx-model/blob/master/src/api.js) appears to not conflict with superagent `1.x`'s API, I have pointed out that mobx-model relies on a version of superagent with which superagent-cache is not compatible. It's completely possible that their usage is not compatible with superagent `1.x`.

You've told me that passing a pre-patched superagent instance into mobx-model fails. That's a good note. However, until I have more information--an error message or an open-source repo in which I can view a simple, isolated demonstration of the failure--I cannot help you.

**Comment by vijayst** [comment]
There is no failure as an error or exception. I patch superagent with superagent-cache. It does a fine job of caching everything. I have a refresh method which is supposed to get the latest data. I want to use forceUpdate as one of the params. The forceUpdate param does not work as mobx-model / API does not consider that parameter. So, I always get cached data.

The workaround suggested was to pass a non-patched version of superagent to get fresh data. But since superagent is a singleton, I won't be able to provide a non-patched version.

So, what I have decided as work-around is: whenever I want cached data I will pass superagent-cache in the request. Whenever I want fresh data, I will use the default superagent from mobx-model.

But, it will be neat if one of this happens:
- superagent-cache does not patch superagent, but wraps superagent.
- (or) mobx-model works with superagent-cache internally and accepts two additional params: cache: true, forceUpdate: true.

I think superagent-cache works fine with superagent. Before you suggested, I was using superagent-cache on superagent@2 and it works fine.

**Comment by jpodwys** [comment]
Huh, I've never tried superagent-cache with superagent 2.x. Glad to hear it has at least some comparability with superagent-cache. 

So are you trying to use forceUpdate as a param inside of the backgroundRefreah function? Is that where the breakdown happens?

Or do you simply need mobx-model to always use forceUpdate and then need to not use forceUpdate in your other queries? If that's the case, you can already do that. Just set the forceUpdate property to true in the defaults object and then set it to false in each individual query.

**Comment by vijayst** [comment]
That is how I would expect it to work. But mobx-model wraps superagent. And, it does not recognise the forceUpdate param.

**Comment by jpodwys** [comment]
I apologize, it appears that I overlooked your comment earlier about passing `forceUpdate` in the `defaults` object not working. I do not evaluate `forceUpdate` in the `defaults` object because I didn't think it was a use case anyone would want. You can see the function [here](https://github.com/jpodwys/superagent-cache/blob/master/utils.js#L176).

I'll change the behavior and cut a bug fix release tomorrow. Thank you for the report.

**Comment by jpodwys** [comment]
I've created a new issue to track this: #48.

**Comment by vijayst** [comment]
Thank you.

**Comment by jpodwys** [comment]
I listed a branch name in the new issue for you. Please test out that branch to see if it fixes the issue you're seeing. Please let me know if it helps so I can try to get a new release cut tomorrow.
