### ISSUE TITLE
End callback is not called when there is an error on the request

### ISSUE THREAD

**Issue by daf-spr** [jpodwys/superagent-cache#5]
If server returns 404 or another error, end callback gets ignored instead of calling it with the the provided error.

```
superagent
          .get('localhost:3000/invalid')
          .end(function (err, response){
            // Never called
          });
```

**Comment by bceballos** [comment]
I'm still seeing this bug, currently on superagent 3.8.3 I'm doing 
````
superagent.get(url).end((err, result) => {
    if (err) {
        return err;
    } else {
        ...more code here
    }
````
If the url I've provided returns back a 404 the .end will hang and never resolve.

**Comment by jpodwys** [comment]
I'm sorry you're seeing this issue. I'm not available to look into this, but if you'd like to submit a PR, I'd be happy to review/merge/release an update. Alternatively, you could check out `superagent-cache-plugin` to see if it has the same issue.
