### ISSUE TITLE
._end naming collision

### ISSUE THREAD

**Issue by jpodwys** [jpodwys/superagent-cache#52]
In a `superagent` release some time since `1.8.0`, the superagent team has begun using `request._end` internally. Because this is something `superagent-cache` has done for a long time, there is now a naming collision for users of more recent versions of `superagent`.

Because `._end` is listed as an API method in `superagent-cache`'s docs, the only way to avoid the name collision is to release a breaking change (`2.x`) of `superagent-cache` that changes my `._end` function's name.

Because there are a number of things I'd like to include in `superagent-cache`'s `2.x` release (including compatibility with the latest `superagent` releases as well as everything listed in #25), fixing this issue is not trivial. My goal of keeping `superagent-cache` and all of its related cache modules as well as `superagent-cache-plugin` in major release sync only increases the maintenance burden.

If this bug is causing you problems, please comment on this issue.

**Comment by kangaroo5383** [comment]
This is preventing us from using this, is there a workaround atm?

**Comment by jpodwys** [comment]
Have you tried using superagent-cache-plugin? It doesn't have this issue.

**Comment by jpodwys** [comment]
@kangaroo5383 does superagent-cache-plugin meet your needs, or would your use case benefit from using superagent-cache?
