### ISSUE TITLE
Is this only for superagent v1.x ?

### ISSUE THREAD

**Issue by refaelos** [jpodwys/superagent-cache#53]
I think Superagent is already on its 3.x version ... is this cache only for v1.x?

If yes, how do I activate cache on Superagent 3.x?

Thanks!

**Comment by refaelos** [comment]
@jpodwys what other options do you know of making superagent's requests cached ?

**Comment by jpodwys** [comment]
So, potentially good news.

I just ran my `superagent-cache-plugin` unit tests against the latest superagent `2.x` and `3.x` and all unit tests passed. This isn't a guarantee that it will work for you, but it's quite promising.

However, if it doesn't end up working for you, then I'm afraid there are no real alternatives out there. I just looked on NPM and there are no other superagent caching modules out there that have been updated within the past 24 months. Additionally, even those ones have fewer features than my modules.

So please try it out with superagent `3.x` and let me know how it goes. If it fails, I'd say that your best options are:

1. Let's get superagent-cache and superagent-cache-plugin compatible with superagent 3.x
2. Write your own minimal superagent 3.x-compatible plugin (although if you're going to go through the effort, you might as well PR to superagent-cache)
3. Do caching by hand inside each of your superagent response handler callbacks

**Comment by refaelos** [comment]
I just wonder why the browser cache isn't used or there's no way to activate it...?

**Comment by jpodwys** [comment]
If you're asking how you can use `localStorage` or `sessionStorage`, you can do so as follows:

```js
var superagent = require('superagent-cache')(null, {storage: 'session'});
```

As detailed in the [this section](https://github.com/jpodwys/superagent-cache#how-do-i-use-a-custom-configuration) of superagent-cache's docs, the second param passed to superagent-cache's constructor is either a cache to be used or a config object to be consumed by superagent-cache's bundled cache module.

**Comment by refaelos** [comment]
Thanks for all the answers!
Appreciate it.
