### ISSUE TITLE
A custom cache implementation for a redux-store ??

### ISSUE THREAD

**Issue by fabm22** [jpodwys/superagent-cache#57]
Hi, 

Regarding this global patch cache or the plugin version, seeing the list of supported [caches](https://github.com/jpodwys/superagent-cache#supported-caches), I find no documentation on how to, maybe, implement a custom store, in my case using a redux-store, since my app ALREADY basically stores the data from the server in a store, would be no need to duplicate in memory cache the same data.

Is this possible ?

(Also, unrelated, but are the ```defaultExpiration: 60``` in doc in seconds ?)

Thanks a lot.

**Comment by jpodwys** [comment]
Yes, `defaultExpiration` is in seconds.

If I understand your first question correctly, you're wanting to create a custom piece of code for superagent-cache that dispatches superagent responses directly to your redux store. Is that right?

If that's correct and, as you say, you have no need "to duplicate in memory cache the same data," then it sounds like you don't need superagent-cache at all. In fact, you could do so very easily with regular old superagent using code similar to the following:

```js
const getEntry = function(id) {
  superagent.get('/my/api/entry/' + id).then(entry => {
    store.dispatch(/* YOUR STUFF GOES HERE */);
  });
}
```

**Comment by jpodwys** [comment]
Yes, `defaultExpiration` is in seconds.

If I understand your first question correctly, you're wanting to create a custom piece of code for superagent-cache that dispatches superagent responses directly to your redux store. Is that right?

General instructions for writing your own cache module that can be used with superagent-cache can be found [here](https://github.com/jpodwys/cache-service#cache-module-interface). The simplest way to do this is probably just to model your implementation after [this one](https://github.com/jpodwys/cache-service-cache-module/blob/master/cacheModule.js).

It sounds to me like you'll want your cache module's `set` function to call `store.dispatch(/* ... */);` and you'll want your `get` function to check your store for the data your superagent call would have fetched.

To help you with this, superagent-cache [generates a cache key](https://github.com/jpodwys/superagent-cache/blob/master/superagentCache.js#L140) to use with the cache you provide to it. That key gets passed to your cache module's API functions. You can use that key somehow to set data into your redux store and to check whether that data exists before executing a query.

**Comment by jpodwys** [comment]
Does this answer your question?

**Comment by fabm22** [comment]
Thanks for you answer.
