### ISSUE TITLE
Not clear how to invalidate/disable all cache

### ISSUE THREAD

**Issue by arjunmehta** [jpodwys/superagent-cache#60]
Thank you for such a great plugin!

It's not entirely clear on how to invalidate all cache or turn caching on/off, (useful when a user logs out of the service, I want to invalidate all cached data).

I'd imagine it might look something like:
```javascript
superagentCache(superagent, {enabled: false}); // disables
superagentCache(superagent, {enabled: true}); // re-enables
```
Perhaps there is already a way to do this, but it's not entirely clear from the otherwise very thorough docs. Any help would be appreciated. And I'd be willing to contribute to the project if you feel this may be useful as well.

**Comment by jpodwys** [comment]
I'm happy to hear you're enjoying the library! Sounds like you're interested in 1) flushing the entire cache and 2) conditionally preventing caching. You have a few options!

## Invalidating the Cache

#### 1) superagent-cache Public API

> If I understand your use case correctly, I recommend this solution.

The cache provided to `superagent-cache` [is available as follows](https://github.com/jpodwys/superagent-cache#cache):

```js
superagentCache.cache.flush();
```

#### 2) cache module Public API

If you prefer, you can also call the public methods on the cache you pass to `superagent-cache` if you have a reference to it:

```js
var superagent = require('superagent');
var redisModule = require('cache-service-redis');
var redisCache = new redisModule({redisEnv: 'REDISCLOUD_URL'});
var defaults = {cacheWhenEmpty: false, expiration: 900};
require('superagent-cache')(superagent, redisCache, defaults);

// Later in the code
redisCache.flush();
```

## Conditionally Preventing Caching

If you have some indicator of whether a user is logged in available everywhere, you can conditionally set the `expiration` property on all necessary queries.

```js
superagent
  .get(uri)
  .expiration(loggedIn ? 900 : 0)
  .end(function (error, response){
    // handle response
  }
);
```

**Comment by arjunmehta** [comment]
@jpodwys Wow thank you for such a thorough response. 👍 Makes sense!

Perhaps the docs would really benefit from a blurb about managing the actual cache and link to your [cache-service-cache-module](https://github.com/jpodwys/cache-service-cache-module) package.

In this case, `cache.flush()` and conditional `expiration` is exactly what I was looking for.

Thank you again! I'll leave it up to you to close the issue as you see fit.

**Comment by jpodwys** [comment]
Glad I could help and thanks for the note. I have the info sprinkled throughout the docs but something more explicit would certainly be helpful. You're not the first person to be unsure about how to do this sort of thing so I ought to clear it up! :)
