### ISSUE TITLE
Why not cache `response.type`?

### ISSUE THREAD

**Issue by kostiako** [jpodwys/superagent-cache#63]
Responses' content-type is quite an important piece of information.

Quite often the client side bases its behavior solely on the `content-type` of the response received so that custom parsing/interpreting logic could be applied. 

Currently, this is unattainable.

**Comment by jpodwys** [comment]
Sounds like the [`prune` method](https://github.com/jpodwys/superagent-cache/blob/master/README.md#prunecallback-response) is what you want. Combine it with the [`defaults` object]  (https://github.com/jpodwys/superagent-cache/blob/master/README.md#how-do-i-use-a-custom-configuration), and you're set!

**Comment by romaleev** [comment]
`prune` method is not a solution if you apply `superagent-cache` globally like
```
var superagent = require('superagent');
require('superagent-cache')(superagent);
```
Adding `response.type` to other cached properties would solve the issue

**Comment by jpodwys** [comment]
I agree, your solution to modify the `superagent-cache`'s source would do the trick. However, using `prune` with the `defaults` object would do the trick globally.

```
var superagent = require('superagent');
var defaults = {
  prune: function(response) {
    return {
      // props you want returned from response
    };
  }
};
require('superagent-cache')(superagent, null, defaults);
```

**Comment by kostiako** [comment]
Thanks, @jpodwys , will try this out shortly.

**Comment by kostiako** [comment]
Worked out great!

**Comment by jpodwys** [comment]
Glad to hear it!
