### ISSUE TITLE
Cache Keys are Generated Incorrectly From URLs with Repeated Search Params

### ISSUE THREAD

**Issue by chriswsh** [jpodwys/superagent-cache#65]
**Issue**

Some URLs use repeated search parameters to take advantage of the automatic node/express consolidation into arrays, (`https://example.com/search?sort[]=key1_asc&sort[]=key2_desc`). When creating the cache key from the URL, the values aren't concatenated. Instead, the last value in the list is used.

This leads to situations where the cache isn't properly registering that the agent is trying to query a different URL. (`https://example.com/search?sort[]=key1_desc&sort[]=key2_desc` would get the same cache key.)

**Comment by jpodwys** [comment]
Interesting! I originally wrote this library during a time when superagent itself did not support multiple query params of the same name. I'm happy to know they've fixed that.

I'm not currently in a place where I have time to address this. However, [here](https://github.com/jpodwys/superagent-cache/blob/master/utils.js#L30) is the code responsible for acquiring query params for cache key generation. If you'd like to try your hand at updating the code, I'd be happy to review your PR.

**Comment by chriswsh** [comment]
How's this?

https://github.com/jpodwys/superagent-cache/pull/66

**Comment by jpodwys** [comment]
Thank you for being willing to add this change! Published to NPM as `3.1.1`.

**Comment by chriswsh** [comment]
You're welcome!
