### ISSUE TITLE
v.4 and v.5 compatibility

### ISSUE THREAD

**Issue by mvasin** [jpodwys/superagent-cache#67]
Hi! The readme mentions compatibility with superagent v.2 and v.3. What about v.4 and v.5?

**Comment by jpodwys** [comment]
Great question! The good news is that I just ran this repo's unit tests against superagent 4 and 5 and they all pass! That said, I haven't attempted to use this library with the latest versions of superagent, so I may be missing something. But, in my opinion, the unit tests passing suggest it's worth trying out :)
